### ISSUE TITLE
Getting error after update NuGet package Akka.Persistence.SqlServer

### ISSUE THREAD

**Issue by Pudev** [akkadotnet/Akka.Persistence.SqlServer#26] opened 2016-04-15 11:10 UTC
After updating the NuGet package to version 1.0.6.3 I'm getting an error:

> [Thread 0014][akka://TaskManagementSystem/system/akka.persistence.journal.sql-server] Object reference not set to an instance of an object.
> Cause: [akka://TaskManagementSystem/system/akka.persistence.journal.sql-server]: Akka.Actor.ActorInitializationException: Exception during creation ---> System.NullReferenceException: Object reference not set to an instance of an object.

Without changing anything to the project I have made downgrade to the package 1.0.6.0 and my system starter working propertly.

**Comment by Horusiath** [comment] 2016-04-15 15:28
This is probably an issue with regression, we detected in https://github.com/akkadotnet/akka.net/issues/1861.

**Comment by Aaronontheweb** [comment] 2016-04-15 15:39
@Horusiath your call - we can do a new release any time. Should we go forward with a 1.0.8 now?

**Comment by Pudev** [comment] 2016-04-15 15:50
@Horusiath I just read the issue [(https://github.com/akkadotnet/akka.net/issues/1861)] that you mention. I have explicitly configured the journal settings.

**Comment by TheeJamesLee** [comment] 2016-04-18 12:11
Hi,  I'm also hitting the same problem as @Pudev  where using the 1.0.6.3-beta package from NuGet I have the exact same error.  The rest of the Akka system is all @ 1.0.7 or 1.0.7.18-beta where possible and I think this is actually the problem.  I also have the akka.persistence.journal.plugin explicitly defined in the hocon.

I have taken the latest dev branch of this Akka.Persistence.SQLServer repo this morning that contains @alexvaluyskiy 's work moving it to 1.0.7 and as a quick test dropping this this DLL in the bin folder of our compiled service (replacing the 1.0.6.3-beta package dll).
This appears to have solved that issue.

Is it possible to put out the dev branch as a 1.0.7.1-beta package as a thought?

**Comment by Danthar** [comment] 2016-04-18 13:06
The latest Akka.Persistence.SqlServer is available on the nightlies feed.

**Comment by TheeJamesLee** [comment] 2016-04-18 13:40
@Danthar thank you for that - I'd completely forgotten about the nightlies in the docs.  I just tested the application against the latest with those sources and for me the issue is resolved and everything looks good.  Thanks.

**Comment by Pudev** [comment] 2016-04-19 10:25
Also test with the version 1.0.7.90 of Akka.Persistence.SqlServer from the nightlies feed and it seems it works fine.

**Closed** 2016-08-02 10:20 UTC
